### PR TITLE
GameSpace: Enable oplus game_switch_enable node if exists

### PR DESCRIPTION
**Pull request by ishugrapher**
* Increases touch sampling in oplus devices

### CODE REVIEW

**Comment by neobuddy89** [comment]
is there way to allow overriding /proc/touchpanel/game_switch_enable via xml?

**Comment by ishugrapher** [comment]
> is there way to allow overriding /proc/touchpanel/game_switch_enable via xml?

Are you asking about to change the path of node through strings.xml?

**Comment by gwolf2u** [comment]
> > is there way to allow overriding /proc/touchpanel/game_switch_enable via xml?
> 
> Are you asking about to change the path of node through strings.xml?

kind of
think the idea is to have a overlay for it if possible

**Comment by ishugrapher** [comment]
> > > is there way to allow overriding /proc/touchpanel/game_switch_enable via xml?
> > 
> > 
> > Are you asking about to change the path of node through strings.xml?
> 
> kind of think the idea is to have a overlay for it if possible

Hmm ok

**Pull request closed without merging**
